<h1>Getting Started with Matrices</h1>

Let's import a matrix from the provided file.  It can be found at https://archive.ics.uci.edu/ml/datasets/seeds

In [3]:
import numpy as np
seeds = np.loadtxt("data/seeds_dataset.txt",dtype=np.float64)

Column meanings for the seeds dataset
1. area A, 
2. perimeter P, 
3. compactness C = 4*pi*A/P^2, 
4. length of kernel, 
5. width of kernel, 
6. asymmetry coefficient 
7. length of kernel groove. 

In [4]:
print(seeds[1:10,:])

[[ 14.88    14.57     0.8811   5.554    3.333    1.018    4.956    1.    ]
 [ 14.29    14.09     0.905    5.291    3.337    2.699    4.825    1.    ]
 [ 13.84    13.94     0.8955   5.324    3.379    2.259    4.805    1.    ]
 [ 16.14    14.99     0.9034   5.658    3.562    1.355    5.175    1.    ]
 [ 14.38    14.21     0.8951   5.386    3.312    2.462    4.956    1.    ]
 [ 14.69    14.49     0.8799   5.563    3.259    3.586    5.219    1.    ]
 [ 14.11    14.1      0.8911   5.42     3.302    2.7      5.       1.    ]
 [ 16.63    15.46     0.8747   6.053    3.465    2.04     5.877    1.    ]
 [ 16.44    15.25     0.888    5.884    3.505    1.969    5.533    1.    ]]


Attributes for matrices, try tab completion to see available methods

In [9]:
print("type: {}\nndim: {}\nshape:{}\nsize:{}\ndtype:{}".format(
    type(seeds),seeds.ndim,seeds.shape,seeds.size,seeds.dtype))

type: <class 'numpy.ndarray'>
ndim: 2
shape:(210, 8)
size:1680
dtype:float64


In [11]:
n,p = seeds.shape #Remember tuple unpacking!

Let's initialize another array with a list

In [12]:
onelist = [1.0]*n
onevec = np.array(onelist)
print(onevec.dtype)
print(onevec.shape)
print(onevec)

float64
(210,)
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


We can transpose really easily...

In [13]:
print(seeds.T.shape)
print(seeds.T)

(8, 210)
[[ 15.26    14.88    14.29   ...,  13.2     11.84    12.3   ]
 [ 14.84    14.57    14.09   ...,  13.66    13.21    13.34  ]
 [  0.871    0.8811   0.905  ...,   0.8883   0.8521   0.8684]
 ..., 
 [  2.221    1.018    2.699  ...,   8.315    3.598    5.637 ]
 [  5.22     4.956    4.825  ...,   5.056    5.044    5.063 ]
 [  1.       1.       1.     ...,   3.       3.       3.    ]]


What should happen if we do the following?

In [14]:
print(seeds.T.dot(onevec))
print(np.sum(seeds,axis=0)) #sum along one axis - vectorization!

[ 3117.98    3057.45     182.9097  1181.992    684.307    777.0422
  1135.695    420.    ]
[ 3117.98    3057.45     182.9097  1181.992    684.307    777.0422
  1135.695    420.    ]


Let's think about a way to do this without numpy...

In [15]:
def mult_ones(seeds):
    output = [0.]*p
    for row in seeds: #arrays are iterable and return the rows
        for i in range(p):
            output[i] += row[i]
    return output

In [18]:
%timeit output = mult_ones(seeds)

The slowest run took 7.28 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 661 µs per loop


In [19]:
%timeit seeds.T.dot(onevec)

The slowest run took 211.48 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 1.95 µs per loop


In [162]:
## Special matrices
onesmat = np.ones((4,4))
zerosmat = np.zeros((4,4))
print(onesmat)
print(zerosmat)
ident = np.eye(4)
print(ident)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


This is quite a bit faster!

<h1>Matrix Slicing</h1>

In [20]:
print(seeds.shape)
seeds.shape = (n*p) #oops!
print(seeds)
seeds = seeds.reshape((n,p))
print(seeds)

(210, 8)
[ 15.26   14.84    0.871 ...,   5.637   5.063   3.   ]
[[ 15.26    14.84     0.871  ...,   2.221    5.22     1.    ]
 [ 14.88    14.57     0.8811 ...,   1.018    4.956    1.    ]
 [ 14.29    14.09     0.905  ...,   2.699    4.825    1.    ]
 ..., 
 [ 13.2     13.66     0.8883 ...,   8.315    5.056    3.    ]
 [ 11.84    13.21     0.8521 ...,   3.598    5.044    3.    ]
 [ 12.3     13.34     0.8684 ...,   5.637    5.063    3.    ]]


In [24]:
#Here are some examples of slicing!
print(seeds[10:20,:].shape)
print(seeds[:,0:4].shape)
print(seeds[10:20,0:4].shape)
print(seeds[:,-4:].shape)

(10, 8)
(210, 4)
(10, 4)
(210, 4)


In [29]:
print("sum: {}\nmean: {}\nmin: {}\nmax: {}".format(
    seeds.sum(), seeds.mean(), seeds.min(), seeds.max()))

sum: 10557.3759
mean: 6.284152321428571
min: 0.7651
max: 21.18


In [30]:
ran = np.arange(20)
print(ran)
ran.mean()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


9.5

In [31]:
print("sum: {}\nmean: {}\nmin: {}\nmax: {}".format(
    seeds.sum(axis=0), seeds.mean(axis=0), 
    seeds.min(axis=0), seeds.max(axis=0)))

sum: [ 3117.98    3057.45     182.9097  1181.992    684.307    777.0422
  1135.695    420.    ]
mean: [ 14.84752381  14.55928571   0.87099857   5.62853333   3.25860476
   3.70020095   5.40807143   2.        ]
min: [ 10.59    12.41     0.8081   4.899    2.63     0.7651   4.519    1.    ]
max: [ 21.18    17.25     0.9183   6.675    4.033    8.456    6.55     3.    ]


In [32]:
print(seeds.cumsum(axis=0)) #really handy!

[[  1.52600000e+01   1.48400000e+01   8.71000000e-01 ...,   2.22100000e+00
    5.22000000e+00   1.00000000e+00]
 [  3.01400000e+01   2.94100000e+01   1.75210000e+00 ...,   3.23900000e+00
    1.01760000e+01   2.00000000e+00]
 [  4.44300000e+01   4.35000000e+01   2.65710000e+00 ...,   5.93800000e+00
    1.50010000e+01   3.00000000e+00]
 ..., 
 [  3.09384000e+03   3.03090000e+03   1.81189200e+02 ...,   7.67807200e+02
    1.12558800e+03   4.14000000e+02]
 [  3.10568000e+03   3.04411000e+03   1.82041300e+02 ...,   7.71405200e+02
    1.13063200e+03   4.17000000e+02]
 [  3.11798000e+03   3.05745000e+03   1.82909700e+02 ...,   7.77042200e+02
    1.13569500e+03   4.20000000e+02]]


In [34]:
## Boolean and list indexing
myrows = [2,17,97]
print(seeds[myrows,0:2])
rowslarge = seeds[:,0]>20
print(rowslarge[0:10])
print(seeds[rowslarge,0:4])

[[ 14.29  14.09]
 [ 15.69  14.75]
 [ 18.98  16.57]]
[False False False False False False False False False False]
[[ 20.71    17.23     0.8763   6.579 ]
 [ 20.2     16.89     0.8894   6.285 ]
 [ 21.18    17.21     0.8989   6.573 ]
 [ 20.88    17.05     0.9031   6.45  ]
 [ 20.1     16.99     0.8746   6.581 ]
 [ 20.97    17.25     0.8859   6.563 ]
 [ 20.03    16.9      0.8811   6.493 ]
 [ 20.24    16.91     0.8897   6.315 ]
 [ 20.16    17.03     0.8735   6.513 ]]


<h1>Matrix operations</h1>

In [36]:
## Some elementwise operations
decseeds = seeds/10.0 
print(decseeds)
mulseeds = 15*seeds - 1.
print(seeds[:,0:-1] - seeds[:,1:])

[[ 1.526    1.484    0.0871  ...,  0.2221   0.522    0.1    ]
 [ 1.488    1.457    0.08811 ...,  0.1018   0.4956   0.1    ]
 [ 1.429    1.409    0.0905  ...,  0.2699   0.4825   0.1    ]
 ..., 
 [ 1.32     1.366    0.08883 ...,  0.8315   0.5056   0.3    ]
 [ 1.184    1.321    0.08521 ...,  0.3598   0.5044   0.3    ]
 [ 1.23     1.334    0.08684 ...,  0.5637   0.5063   0.3    ]]
[[  0.42    13.969   -4.892  ...,   1.091   -2.999    4.22  ]
 [  0.31    13.6889  -4.6729 ...,   2.315   -3.938    3.956 ]
 [  0.2     13.185   -4.386  ...,   0.638   -2.126    3.825 ]
 ..., 
 [ -0.46    12.7717  -4.3477 ...,  -5.083    3.259    2.056 ]
 [ -1.37    12.3579  -4.3229 ...,  -0.762   -1.446    2.044 ]
 [ -1.04    12.4716  -4.3746 ...,  -2.663    0.574    2.063 ]]


In [39]:
## Elementwise functions
print(np.log(decseeds)[0:2,0:2])
print(np.exp(decseeds)[0:2,0:2])
print(np.sqrt(decseeds)[0:2,0:2])

[[ 0.42264993  0.39474114]
 [ 0.39743294  0.37637953]]
[[ 4.59974101  4.41055265]
 [ 4.4282302   4.29306101]]
[[ 1.23531373  1.21819539]
 [ 1.21983605  1.20706255]]


Recall that the empirical covariance matrix is 
$$ 
\hat \Sigma_{j,k} = \frac{1}{n-1} \sum_{i=1}^n (x_{i,j} - \bar x_j) (x_{i,k} - \bar x_k)
$$

In [40]:
## Normalization of a matrix
seedcentered = seeds - seeds.mean(axis=0)
print(seedcentered[0:2,0:2])
seedcov = seedcentered.T.dot(seedcentered) / (n-1)
print(seedcov[0:2,0:2])

[[ 0.41247619  0.28071429]
 [ 0.03247619  0.01071429]]
[[ 8.42603482  3.76045061]
 [ 3.76045061  1.69740663]]


In [42]:
## Some linear algebra operations
print(seedcov.trace())
print(np.linalg.eig(seedcov)) #TDB

13.6183448104
(array([  1.08364768e+01,   2.31997067e+00,   3.95063452e-01,
         5.42424532e-02,   8.45141665e-03,   2.64188341e-03,
         1.47287013e-03,   2.52487858e-05]), array([[  8.79582631e-01,  -1.26116017e-01,   1.08610184e-03,
         -3.03317473e-01,  -1.38879757e-01,  -1.52061885e-01,
          2.74204862e-01,   2.87709147e-02],
       [  3.93152050e-01,  -6.88744128e-02,  -3.78014389e-02,
          3.68106006e-01,   5.50519006e-01,   5.58355464e-01,
         -2.89509008e-01,  -7.14796114e-02],
       [  4.34850558e-03,   3.19106495e-03,   1.10692713e-02,
         -6.22063083e-02,  -6.73806848e-02,  -3.86618542e-02,
         -3.25631128e-02,  -9.94426218e-01],
       [  1.27612344e-01,  -3.59319716e-02,  -5.20419510e-02,
          4.78550309e-01,   2.85063369e-01,  -7.95326618e-01,
         -1.91705751e-01,  -1.21890190e-02],
       [  1.10732226e-01,  -3.08242317e-03,   5.79051315e-02,
         -3.33897486e-01,  -2.50826296e-01,  -6.20307997e-02,
         -8.950558

Stacking arrays:

In [43]:
ratvec = seeds[:,4] / seeds[:,5]
print(ratvec.shape)

(210,)


In [44]:
np.hstack((seeds,ratvec)) #error

ValueError: all the input arrays must have same number of dimensions

In [45]:
ratmat = ratvec.reshape((n,1))
np.hstack((seeds,ratmat))

array([[ 15.26      ,  14.84      ,   0.871     , ...,   5.22      ,
          1.        ,   1.49122017],
       [ 14.88      ,  14.57      ,   0.8811    , ...,   4.956     ,
          1.        ,   3.2740668 ],
       [ 14.29      ,  14.09      ,   0.905     , ...,   4.825     ,
          1.        ,   1.23638385],
       ..., 
       [ 13.2       ,  13.66      ,   0.8883    , ...,   5.056     ,
          3.        ,   0.38869513],
       [ 11.84      ,  13.21      ,   0.8521    , ...,   5.044     ,
          3.        ,   0.78821568],
       [ 12.3       ,  13.34      ,   0.8684    , ...,   5.063     ,
          3.        ,   0.5275856 ]])

In [47]:
everyten = seeds[0:n:10,:]
print(everyten.shape)
np.vstack((seeds,everyten))

(21, 8)


array([[ 15.26  ,  14.84  ,   0.871 , ...,   2.221 ,   5.22  ,   1.    ],
       [ 14.88  ,  14.57  ,   0.8811, ...,   1.018 ,   4.956 ,   1.    ],
       [ 14.29  ,  14.09  ,   0.905 , ...,   2.699 ,   4.825 ,   1.    ],
       ..., 
       [ 11.41  ,  12.95  ,   0.856 , ...,   4.957 ,   4.825 ,   3.    ],
       [ 10.93  ,  12.8   ,   0.839 , ...,   5.398 ,   5.045 ,   3.    ],
       [ 12.38  ,  13.44  ,   0.8609, ...,   5.472 ,   5.045 ,   3.    ]])

In [49]:
## The difference between a copy and assignment
A = np.arange(20)
B = A
A.shape = (10,2)
print(A)
B.shape

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


(10, 2)

In [135]:
A = np.arange(20)
B = A.copy()
A.shape = (10,2)
B.shape

(20L,)